nginx-subfilter-demo:
  image: nginx:latest
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - "8880:80"
#  environment:
#    - NGINX_PORT=80
  links:
    - app
  command: [nginx-debug, '-g', 'daemon off;']

app:
  image: node
  volumes:
    - .:/usr/src/app
  command: node /usr/src/app/server.js
  ports:
    - "5000:5000"
