nginx-subfilter-demo:
  image: nginx:latest
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    - ./etc/nginx/customized/sub_filter_customized.conf:/etc/nginx/conf.d/sub_filter_customized.conf:ro
#    - ./etc/nginx/certificates:/etc/nginx/certificates:ro
  ports:
    - "38880:80"
#    - "38843:443"
    - "18080:8080"
  links:
    - app
  command: [nginx-debug, '-g', 'daemon off;']

app:
  image: node
  volumes:
    - .:/usr/src/app
  command: node /usr/src/app/server.js
  ports:
    - "15000:5000"
